name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['24.1', '23.3']
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: '3.17.0'
      - uses: actions/cache@v2
        name: Cache
        with:
          path: |
            _build
          key: ${{ runner.os }}-build-${{ matrix.otp_version }}-${{ hashFiles(format('rebar.lock')) }}-1
          restore-keys: |
            ${{ runner.os }}-build-${{ matrix.otp_version }}-1-
      - run: rebar3 compile
      - run: rebar3 ct
      - run: pip install --user codecov
        if: ${{ matrix.otp == '24.1' }}
      - run: /home/runner/.local/bin/codecov
        if: ${{ matrix.otp == '24.1' }}
      - run: rebar3 dialyzer
        if: ${{ matrix.otp == '24.1' }}
      - run: rebar3 xref
        if: ${{ matrix.otp == '24.1' }}
