name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['26.0', '25.3', '24.3']
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: '3.21.0'
      - uses: actions/cache@v2
        name: Cache
        with:
          path: |
            _build
          key: ${{ runner.os }}-build-${{ matrix.otp_version }}-${{ hashFiles(format('rebar.lock')) }}-1
          restore-keys: |
            ${{ runner.os }}-build-${{ matrix.otp_version }}-1-
      - run: rebar3 compile
      - run: rebar3 ct
      - run: rebar3 dialyzer
        if: ${{ matrix.otp == '26.0' }}
      - run: rebar3 xref
        if: ${{ matrix.otp == '26.0' }}
      - run: rebar3 as test do cover, covertool generate
        if: ${{ matrix.otp == '26.0' }}
      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        if: ${{ matrix.otp == '26.0' }}
        with:
          file: "_build/test/covertool/segmented_cache.covertool.xml"
